server:
  port: '8080'
  mode: 'debug' # debug, release

database:
  host: 'localhost'
  port: '5432'
  user: 'postgres'
  password: 'postgres'
  dbname: 'tkhanchat'
  sslmode: 'allow'

jwt:
  secret: 'your-secret-key-change-this-in-production'
  access_token_expire_minutes: 15 # 15 minutes
  refresh_token_expire_days: 7 # 7 days
